const Permission = {
    ADMINISTRATOR: "ADMINISTRATOR",
    PANEL_ACCESS : "PANEL_ACCESS",

    CREATE_ROLE: "CREATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    ADD_ROLE: "ADD_ROLE",
    REMOVE_ROLE: "REMOVE_ROLE",

    VIEW_LOGS: "VIEW_LOGS",
};

module.exports = Permission;