const Permission = {
    ADMINISTRATOR: "ADMINISTRATOR",
    PANEL_ACCESS : "PANEL_ACCESS",

    CREATE_ROLE: "CREATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    ADD_ROLE: "ADD_ROLE",
    REMOVE_ROLE: "REMOVE_ROLE",

    VIEW_LOGS: "VIEW_LOGS",

    VIEW_CATEGORY: "VIEW_CATEGORY",
    ADD_CATEGORY: "ADD_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    ADD_SUB_CATEGORY: "ADD_SUB_CATEGORY",
    DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY"
};

module.exports = Permission;