const Permission = {
  ADMINISTRATOR: "ADMINISTRATOR",
  PANEL_ACCESS: "PANEL_ACCESS",

  VIEW_ROLE: "VIEW_ROLE",
  CREATE_ROLE: "CREATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  ADD_ROLE: "ADD_ROLE",
  REMOVE_ROLE: "REMOVE_ROLE",

  VIEW_LOGS: "VIEW_LOGS",

  VIEW_CATEGORY: "VIEW_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  ADD_SUB_CATEGORY: "ADD_SUB_CATEGORY",
  DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",

  VIEW_POSTS: "VIEW_POSTS",
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
  EDIT_POST: "EDIT_POST",
  SITE_SETTING: "SITE_SETTING",
};

module.exports = Permission;